### ISSUE TITLE
Duplicate components are consolidated in deep merge

### ISSUE THREAD

**Issue by rajanikant05** [philips-software/SPDXMerge#25]
Duplicate components are not captured separately in deep merge and due to this traceability is missing as it's consolidated in single component.

**Comment by AnnieJovitha** [comment]
Can you add an example please? and which file format did you face this issue ?

**Comment by yakuri** [comment]
@AnnieJovitha 
Thank you for releasing SPDXMerge.

In some cases, information is missing when the same SPDXID exists in multiple files as shown below.
I think @rajanikant05 asked about this case.

I think the only way to avoid missing information in this case is to use Shallow Merge instead of Deep Merge.

![image](https://user-images.githubusercontent.com/62694113/235426431-14bea7e0-5e13-498f-b880-5ebb7690290e.png)

**Comment by AnnieJovitha** [comment]
Thank you for the examples @yakuri , i will investigate.

**Comment by AnnieJovitha** [comment]
Hi Yakuri, I see where the problem lies, 
1. The SPDXID is a unique Id, so there cant be duplicates.
2. The merged document is again a valid SPDX document, so it cant have duplicates either. 
3. To avoid: The SPDX Id of the child documents should use some package checksum instead of just plain numbers.
eg. SPDXRef-package-0d9a5af1-1663-479e-9fdc-4fa5d3f00342
5. so if there are same packages in two child documents with same identifier, the package section will list one, The relationship section will make it clear to trace the package from two child documents.

Let me know your thoughts on it

**Comment by yakuri** [comment]
Hi AnnieJovitha, Thank you for your reply.

> The merged document package section will list one, The relationship section will make it clear to trace the package from two child documents.

Can you give us one example?

Best regards,

**Comment by yakuri** [comment]
Thank you for your reply.
I have some private matters to attend to and would like to reply on Monday, May 8.
Sorry for the wait.

**Comment by yakuri** [comment]
> Hi Yakuri, I see where the problem lies,
> 
> 1. The SPDXID is a unique Id, so there cant be duplicates.
> 2. The merged document is again a valid SPDX document, so it cant have duplicates either.
> 3. To avoid: The SPDX Id of the child documents should use some package checksum instead of just plain numbers.
>    eg. SPDXRef-package-0d9a5af1-1663-479e-9fdc-4fa5d3f00342
> 4. so if there are same packages in two child documents with same identifier. The merged document package section will list one, The relationship section will make it clear to trace the package from two child documents.
> 
> Let me know your thoughts on it



> This is how your merged SBOM should look like from your above examples, provided that the SPDX id is unique (following the point no. 3)and if its the same package listed in two child sboms. <img alt="Screenshot 2023-05-04 at 10 53 22" width="512" src="https://user-images.githubusercontent.com/17983615/236156934-e7b416bc-a3af-4bf3-8dab-acb3cfe6e948.png">



> Note: if you dont create unique SPDX ids in the child SBOMs then the package will indeed be lost and this is an expected behaviour
